
USE [QLPhongMachTu]
GO

/* BẢNG LOẠI THUỐC*/
GO
INSERT INTO LOAITHUOC values ('T02', 'codein', 'DV01', 3000 )
GO
INSERT INTO LOAITHUOC values ('T03', 'chericof', 'D02', 2000 )
GO
INSERT INTO LOAITHUOC values ('T04', 'calyptin', 'D02', 9000 )
GO

GO
SELECT * FROM LOAITHUOC
GO

/* BẢNG ĐƠN VỊ*/
GO 
INSERT INTO DONVI values ('DV02', 'chai')
GO

GO
SELECT * FROM DONVI
GO

/*BẢNG DS BỆNH NHÂN*/
GO
INSERT INTO BENHNHAN values ('BN01', N'Cao Thị Phương Loan', N'Nữ', '08/04/2000', 'Gia Lai')
INSERT INTO BENHNHAN values ('BN02', N'Phạm Ngọc Linh', N'Nữ', '16/04/2000', N'Vũng Tàu')
GO

SET IDENTITY_INSERT  ON

GO
SELECT * FROM BENHNHAN
GO

/*BẢNG DS KHÁM BỆNH*/

GO
INSERT INTO DS_KHAMBENH values ('DS01', '19/12/2020', 'BN01')
GO

GO
SELECT * FROM DS_KHAMBENH

SELECT COUNT (*) FROM DS_KHAMBENH
GO

/*BẢNG PHIẾU KHÁM BỆNH*/

GO
SELECT * FROM PHIEUKHAM

SELECT MaBN, HoTen, GioiTinh, NamSinh, DiaChi FROM BENHNHAN WHERE (MaBN like '%%')

SELECT MaBN, HoTen, GioiTinh, NamSinh, DiaChi FROM BENHNHAN WHERE ( HoTen like '%Loan%')


SELECT *
FROM DS_KHAMBENH DS

SELECT *
FROM DONTHUOC

SELECT *
FROM DS_KHAMBENH

/*BẢNG DS KHÁM BỆNH VÀ BỆNH NHÂN*/
SELECT DS_KHAMBENH.NgayKham, DS_KHAMBENH.MaBN, BENHNHAN.HoTen, BENHNHAN.GioiTinh, BENHNHAN.NamSinh, BENHNHAN.DiaChi
FROM DS_KHAMBENH , BENHNHAN 
WHERE DS_KHAMBENH.MaBN = BENHNHAN.MaBN

INSERT INTO DS_KHAMBENH (NgayKham, MaBN)
SELECT MaBN, HoTen, GioiTinh, NamSinh, DiaChi
FROM BENHNHAN

SELECT DS_KHAMBENH.NgayKham, BENHNHAN.MaBN, BENHNHAN.HoTen, BENHNHAN.GioiTinh, BENHNHAN.NamSinh, BENHNHAN.DiaChi 
FROM DS_KHAMBENH, BENHNHAN 
WHERE DS_KHAMBENH.MaBN = BENHNHAN.MaBN

/*HÓA ĐƠN, PHIẾU KHÁM VÀ BỆNH NHÂN*/
SELECT HOADON.NgayHD, PHIEUKHAM.MaPhieuKham, BENHNHAN.MaBN, BENHNHAN.HoTen, BENHNHAN.GioiTinh, BENHNHAN.NamSinh, BENHNHAN.DiaChi, HOADON.TienKham, HOADON.TiemThuoc 
FROM HOADON, PHIEUKHAM, BENHNHAN 
WHERE HOADON.MaPhieuKham = PHIEUKHAM.MaPhieuKham AND PHIEUKHAM.MaBN = BENHNHAN.MaBN

/********************/
SELECT HOADON.NgayHD, PHIEUKHAM.MaPhieuKham, BENHNHAN.MaBN, BENHNHAN.HoTen, BENHNHAN.GioiTinh, BENHNHAN.NamSinh, BENHNHAN.DiaChi, HOADON.TienKham, HOADON.TiemThuoc FROM HOADON, PHIEUKHAM, BENHNHAN WHERE HOADON.MaPhieuKham = PHIEUKHAM.MaPhieuKham AND PHIEUKHAM.MaBN = BENHNHAN.MaBN